version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/build-linux-glibc
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /containers/build-linux-musl
    schedule:
      interval: weekly
