<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.idoly</groupId>
        <artifactId>sqlite-jdbc-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>sqlite-native</artifactId>
    <packaging>pom</packaging>
    <name>SQLite Native Build</name>

    <properties>
        <automatic.module.name>io.github.idoly.sqlite.nativelib</automatic.module.name>
    </properties>

    <profiles>
        <profile>
            <id>package-native</id>
            <activation>
                <property>
                    <name>sqlite.native.platform</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>3.4.0</version>
                        <executions>
                            <execution>
                                <id>stage-native-library</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/native-classes</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${sqlite.native.inputDirectory}</directory>
                                            <targetPath>META-INF/native/${sqlite.native.platform}</targetPath>
                                            <filtering>false</filtering>
                                            <includes>
                                                <include>${sqlite.native.inputFile}</include>
                                            </includes>
                                        </resource>
                                        <resource>
                                            <directory>${maven.multiModuleProjectDirectory}</directory>
                                            <targetPath>META-INF</targetPath>
                                            <filtering>false</filtering>
                                            <includes>
                                                <include>LICENSE</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.4.2</version>
                        <executions>
                            <execution>
                                <id>package-native-classifier</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <classesDirectory>${project.build.directory}/native-classes</classesDirectory>
                                    <classifier>${sqlite.native.platform}</classifier>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>attach-native-release</id>
            <activation>
                <property>
                    <name>sqlite.native.releaseDirectory</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>attach-native-classifiers</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>attach-artifact</goal>
                                </goals>
                                <configuration>
                                    <artifacts>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-linux-x86_64-glibc.jar</file>
                                            <type>jar</type>
                                            <classifier>linux-x86_64-glibc</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-linux-aarch64-glibc.jar</file>
                                            <type>jar</type>
                                            <classifier>linux-aarch64-glibc</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-linux-x86_64-musl.jar</file>
                                            <type>jar</type>
                                            <classifier>linux-x86_64-musl</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-linux-aarch64-musl.jar</file>
                                            <type>jar</type>
                                            <classifier>linux-aarch64-musl</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-windows-x86_64.jar</file>
                                            <type>jar</type>
                                            <classifier>windows-x86_64</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-macos-x86_64.jar</file>
                                            <type>jar</type>
                                            <classifier>macos-x86_64</classifier>
                                        </artifact>
                                        <artifact>
                                            <file>${sqlite.native.releaseDirectory}/${project.build.finalName}-macos-aarch64.jar</file>
                                            <type>jar</type>
                                            <classifier>macos-aarch64</classifier>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
