package io.github.idoly.sqlite.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Statement;

/** Centralizes the deliberately narrow JDBC capability policy exposed by this driver. */
final class JdbcSupport {
    private JdbcSupport() {}

    static void validateResultSetMode(
            int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (resultSetType != ResultSet.TYPE_FORWARD_ONLY) {
            throw unsupported("Only forward-only result sets are supported");
        }
        if (resultSetConcurrency != ResultSet.CONCUR_READ_ONLY) {
            throw unsupported("Only read-only result sets are supported");
        }
        if (resultSetHoldability != ResultSet.CLOSE_CURSORS_AT_COMMIT) {
            throw unsupported("Only CLOSE_CURSORS_AT_COMMIT is supported");
        }
    }

    static boolean generatedKeysRequested(int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys == Statement.NO_GENERATED_KEYS) return false;
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) return true;
        throw new SQLException("Invalid generated keys mode: " + autoGeneratedKeys, "HY092");
    }

    static boolean generatedKeysRequested(int[] columnIndexes) throws SQLException {
        if (columnIndexes == null) throw new SQLException("Column indexes cannot be null", "HY009");
        validateGeneratedKeyColumns(columnIndexes.length);
        return columnIndexes.length == 1;
    }

    static boolean generatedKeysRequested(String[] columnNames) throws SQLException {
        if (columnNames == null) throw new SQLException("Column names cannot be null", "HY009");
        validateGeneratedKeyColumns(columnNames.length);
        return columnNames.length == 1;
    }

    static SQLFeatureNotSupportedException unsupported(String message) {
        return new SQLFeatureNotSupportedException(message, "0A000");
    }

    private static void validateGeneratedKeyColumns(int count) throws SQLFeatureNotSupportedException {
        if (count > 1) {
            throw unsupported("SQLite exposes only last_insert_rowid() as a generated key");
        }
    }
}
